// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBqz9NxPxn5FXnYtkcdSnE5H8pX4KyxXs',
    appId: '1:866664891265:web:7232d20caadbec705d1e80',
    messagingSenderId: '866664891265',
    projectId: 'fitnesssync-c8463',
    authDomain: 'fitnesssync-c8463.firebaseapp.com',
    databaseURL: 'https://fitnesssync-c8463-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesssync-c8463.firebasestorage.app',
    measurementId: 'G-EDHCG0VCRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbnOdX6M2mzmqBGyODyd6b2cf2Ghe6lxw',
    appId: '1:866664891265:android:3daa0e7aad92e4125d1e80',
    messagingSenderId: '866664891265',
    projectId: 'fitnesssync-c8463',
    databaseURL: 'https://fitnesssync-c8463-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesssync-c8463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC20gwpm9UWN2kMTlE1ZerSO3qLnTGVR2I',
    appId: '1:866664891265:ios:13f8632a98501f8f5d1e80',
    messagingSenderId: '866664891265',
    projectId: 'fitnesssync-c8463',
    databaseURL: 'https://fitnesssync-c8463-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesssync-c8463.firebasestorage.app',
    iosBundleId: 'fit.rolddevs.fitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC20gwpm9UWN2kMTlE1ZerSO3qLnTGVR2I',
    appId: '1:866664891265:ios:13f8632a98501f8f5d1e80',
    messagingSenderId: '866664891265',
    projectId: 'fitnesssync-c8463',
    databaseURL: 'https://fitnesssync-c8463-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesssync-c8463.firebasestorage.app',
    iosBundleId: 'fit.rolddevs.fitsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBqz9NxPxn5FXnYtkcdSnE5H8pX4KyxXs',
    appId: '1:866664891265:web:73fd476248badb795d1e80',
    messagingSenderId: '866664891265',
    projectId: 'fitnesssync-c8463',
    authDomain: 'fitnesssync-c8463.firebaseapp.com',
    databaseURL: 'https://fitnesssync-c8463-default-rtdb.firebaseio.com',
    storageBucket: 'fitnesssync-c8463.firebasestorage.app',
    measurementId: 'G-WCQ94PJW5S',
  );
}
